language: java
sudo: true
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -yqq graphviz
  - sudo ln -s /usr/bin/dot /usr/local/bin/
